/**
 * Student Portal Gemma 4 AI Service
 * Handles AI Chat Tutor, PDF/Prompt Quiz Fetching, and Post-Quiz AI Performance Analysis.
 */

const SERVER_URL = "http://localhost:5000";

// Helper to call Google Gemini API if user configured key
async function callGeminiApi(promptText, apiKey = "") {
  const key = apiKey || localStorage.getItem("edutrack_gemini_api_key") || "";
  if (!key) return null;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: promptText }] }],
        }),
      }
    );
    if (!response.ok) return null;
    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || null;
  } catch (err) {
    console.warn("Gemini fetch error:", err);
    return null;
  }
}

/**
 * 1. Gemma 4 AI Chat Tutor Response Generator
 */
export async function sendGemmaTutorChat(userText, messagesHistory = [], apiKey = "") {
  // Try Express server first
  try {
    const res = await fetch(`${SERVER_URL}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt: userText, messages: messagesHistory }),
    });
    if (res.ok) {
      const data = await res.json();
      if (data.reply) return data.reply;
    }
  } catch (err) {
    // Server not running, fallback to client-side Gemma 4 engine
  }

  // Try live Gemini API
  const prompt = `You are Gemma 4, an AI Academic Tutor. Answer this student question clearly and encouragingly: "${userText}"`;
  const liveReply = await callGeminiApi(prompt, apiKey);
  if (liveReply) return liveReply;

  // Local Gemma 4 AI Reasoning Engine Fallback
  const q = userText.toLowerCase();
  if (q.includes("dijkstra") || q.includes("shortest path") || q.includes("graph")) {
    return `**Gemma 4 AI Tutor**: Let's break down **Dijkstra's Algorithm**!\n\n` +
      `1. **Core Idea**: Greedy algorithm to find shortest path from single source to all nodes in a weighted graph (non-negative weights).\n` +
      `2. **Data Structure**: Priority Queue (Min-Heap).\n` +
      `3. **Time Complexity**: **O((V + E) log V)** with Binary Heap.\n` +
      `4. **Key Step**: Repeatedly select the unvisited node with smallest distance and relax neighboring edges.\n\n` +
      `Would you like me to quiz you on Graph Algorithms now?`;
  }

  if (q.includes("bst") || q.includes("binary search tree") || q.includes("tree")) {
    return `**Gemma 4 AI Tutor**: Here is a quick guide to **Binary Search Trees (BST)**:\n\n` +
      `- **Invariant**: Left child < Parent < Right child.\n` +
      `- **Search / Insert / Delete**: O(log n) average case, O(n) worst case if skewed.\n` +
      `- **In-Order Traversal**: Always visits nodes in **strictly ascending order**!\n\n` +
      `Tip: For guaranteed O(log n) operations, self-balancing trees like AVL or Red-Black trees are used.`;
  }

  if (q.includes("dbms") || q.includes("sql") || q.includes("normalization")) {
    return `**Gemma 4 AI Tutor**: Let's review **Database Normalization**:\n\n` +
      `- **1NF**: Atomic values, no repeating groups.\n` +
      `- **2NF**: In 1NF + no partial dependency on composite primary key.\n` +
      `- **3NF**: In 2NF + no transitive dependencies.\n` +
      `- **BCNF**: Strict 3NF where every determinant is a candidate key.`;
  }

  return `**Gemma 4 AI Tutor**: Excellent question regarding **"${userText}"**!\n\n` +
    `Here is how to approach this concept:\n` +
    `1. **Understand Core Definitions**: Review fundamental properties and syntax.\n` +
    `2. **Analyze Example**: Work through sample inputs and boundary cases.\n` +
    `3. **Practice**: Test your knowledge with practice quizzes generated by your professor's Gemma 4 AI generator!`;
}

/**
 * 2. Get Published Quizzes (Teacher Dashboard -> Student Portal)
 */
export function getPublishedQuizzes() {
  const localSaved = localStorage.getItem("edutrack_published_quizzes");
  let quizzes = [];
  if (localSaved) {
    try {
      quizzes = JSON.parse(localSaved);
    } catch (e) {}
  }

  const defaultQuizzes = [
    {
      id: 1,
      title: "Data Structures: BST & Graph Traversal",
      course: "Data Structures & Algorithms",
      courseCode: "CS201",
      qCount: 3,
      time: 10,
      diff: "Medium",
      success: "88%",
      color: "green",
      questions: [
        {
          id: 1,
          text: "What is the worst-case time complexity of searching in a balanced Binary Search Tree (BST)?",
          options: [
            { id: "A", text: "O(1)" },
            { id: "B", text: "O(log n)" },
            { id: "C", text: "O(n)" },
            { id: "D", text: "O(n log n)" },
          ],
          correct: "B",
          explanation: "In a balanced BST, tree height is log2(n), giving O(log n) search time.",
        },
        {
          id: 2,
          text: "Which traversal strategy explores graph vertices level by level using a Queue?",
          options: [
            { id: "A", text: "Depth-First Search (DFS)" },
            { id: "B", text: "Breadth-First Search (BFS)" },
            { id: "C", text: "In-order Traversal" },
            { id: "D", text: "Post-order Traversal" },
          ],
          correct: "B",
          explanation: "BFS processes nodes level by level using FIFO Queue operations.",
        },
        {
          id: 3,
          text: "Dynamic Programming requires problems to possess optimal substructure and overlapping subproblems.",
          options: [
            { id: "A", text: "True" },
            { id: "B", text: "False" },
          ],
          correct: "A",
          explanation: "These two properties are mandatory for dynamic programming memoization.",
        },
      ],
    },
    {
      id: 2,
      title: "DBMS: SQL Joins & Normalization",
      course: "Database Management Systems",
      courseCode: "CS302",
      qCount: 2,
      time: 8,
      diff: "Easy",
      success: "92%",
      color: "green",
      questions: [
        {
          id: 1,
          text: "Which SQL JOIN returns all records when there is a match in either left or right table?",
          options: [
            { id: "A", text: "INNER JOIN" },
            { id: "B", text: "LEFT JOIN" },
            { id: "C", text: "FULL OUTER JOIN" },
            { id: "D", text: "CROSS JOIN" },
          ],
          correct: "C",
          explanation: "FULL OUTER JOIN combines results of both LEFT and RIGHT joins.",
        },
        {
          id: 2,
          text: "A database relation is in 3NF if it is in 2NF and has no transitive dependencies.",
          options: [
            { id: "A", text: "True" },
            { id: "B", text: "False" },
          ],
          correct: "A",
          explanation: "3NF explicitly eliminates non-key dependencies (transitive dependencies).",
        },
      ],
    },
  ];

  return [...quizzes, ...defaultQuizzes];
}

/**
 * 3. Analyze Student Quiz Results with Gemma 4
 */
export async function analyzeStudentQuizResults(quiz, studentAnswers) {
  let score = 0;
  const total = quiz.questions.length;
  const questionBreakdown = [];

  quiz.questions.forEach((q) => {
    const studentChoice = studentAnswers[q.id];
    const isCorrect = studentChoice === q.correct || studentChoice === q.answer;
    if (isCorrect) score += 1;

    questionBreakdown.push({
      questionId: q.id,
      questionText: q.text || q.question,
      studentChoice: studentChoice || "Not Answered",
      correctChoice: q.correct !== undefined ? q.correct : q.options?.[q.answer],
      isCorrect,
      explanation: q.explanation || "Gemma 4 Verified Concept.",
    });
  });

  const percentage = Math.round((score / total) * 100);

  let grade = "F";
  if (percentage >= 90) grade = "A+";
  else if (percentage >= 80) grade = "A";
  else if (percentage >= 70) grade = "B";
  else if (percentage >= 60) grade = "C";

  // Sync score back to student records for teacher dashboard
  syncStudentScoreToTeacherDashboard(quiz.courseCode || "CS201", percentage);

  return {
    quizTitle: quiz.title,
    score,
    total,
    percentage,
    grade,
    questionBreakdown,
    summary: `Gemma 4 AI Performance Diagnostic: You scored ${percentage}% (${score}/${total}). ${
      percentage >= 80
        ? "Outstanding mastery of core concepts!"
        : percentage >= 60
        ? "Good performance, but review missed questions to achieve excellence."
        : "Targeted revision required. Review the explanation breakdown below."
    }`,
    weakTopics:
      percentage < 80
        ? ["Time/Space Complexity", "Edge Case Problem Solving"]
        : ["No critical weak areas identified!"],
    actionPlan: [
      `Review explanations for the ${total - score} incorrect questions.`,
      `Practice 5 similar problems in the Gemma 4 AI Tutor chat.`,
      `Re-attempt this quiz to target 100% score mastery.`,
    ],
  };
}

/**
 * 4. Helper: Sync quiz score to teacher dashboard local storage
 */
function syncStudentScoreToTeacherDashboard(courseCode, percentage) {
  const savedStudents = localStorage.getItem("edutrack_students");
  if (savedStudents) {
    try {
      const students = JSON.parse(savedStudents);
      // Update Alex Rivera or first student matching course
      const updated = students.map((s) => {
        if (s.id === 1 || s.courseCode === courseCode) {
          const updatedSubj = { ...s.subjects, "Latest Quiz": percentage };
          return { ...s, subjects: updatedSubj, lastActive: "Just now" };
        }
        return s;
      });
      localStorage.setItem("edutrack_students", JSON.stringify(updated));
    } catch (e) {}
  }
}
